Assignment 1 

Question 1.1

In [ ]:
import numpy as np
n1 = np.zeros(10)
n1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
n2 = np.ones(10)
n2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n1=np.full((1,10),5)
n1

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

Question 1.2 create an array of all the even
integers from 10 to 50

In [ ]:
import numpy as np
print("array of all the even integers from 10 to 50 : ",end="")
arr = np.arange(10,50,2)
arr

array of all the even integers from 10 to 50 : 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Question 1.3 Generate number between 0 and 1

In [ ]:
import numpy as np
print("Random number between 0 and 1 : ")
arr = np.random.rand()
arr

Random number between 0 and 1 : 


0.8103906576719697

Question 1.4 Save and load the matrix

In [102]:
import numpy as np
arr = np.random.randint(10,size=(3,3))
np.savetxt('123.txt', arr)
np.loadtxt('123.txt')
arr

array([[3, 3, 5],
       [3, 5, 4],
       [5, 7, 4]])

Question 2.3 Pandas program to create the today's date


In [ ]:

from datetime import datetime

print("Today's Date : ",end="")
print(datetime.now().date())


Today's Date : 2021-08-09


In [ ]:
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-08-09 00:00:00


Question no. 2(1)

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving matrix.png to matrix.png
User uploaded file "matrix.png" with length 15802 bytes


In [103]:
import pandas as pd

from PIL import Image
import numpy as np
  
img = Image.open('matrix.png')

matrix = np.asarray(img)

print(matrix.shape)

df = pd.DataFrame(matrix)
df.to_csv("matrix1.csv")

(262, 291)


Question no. 3 Age calculator

In [97]:
from datetime import date
 
def Age_calculator(birthDate):
    days_in_year = 365.2425   
    age = int((date.today() - birthDate).days / days_in_year)
    return age
         
# Driver code
print(Age_calculator(date(2000,6,12)), "years")

21 years
