In [1]:
import numpy as np
print("The array of 10 zero's : ",end="")
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
import numpy as np
print("The array of 10 one's : ",end="")
arr = np.ones(10)
arr

The array of 10 one's : 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
import numpy as np
print("The array of 10 five : ",end="")
arr = np.ones(10)*5
arr

The array of 10 five : 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
import numpy as np
print("array of all the even integers from 10 to 50 : ",end="")
arr = np.arange(10,50,2)
arr

array of all the even integers from 10 to 50 : 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [68]:
import numpy as np
print("Random number between 0 and 1 : ")
arr = np.random.rand(6)
#arr.shape
#arr=arr.reshape(2,3)

arr

Random number between 0 and 1 : 


array([0.06491643, 0.99313402, 0.92211726, 0.17554249, 0.50925475,
       0.0553155 ])

In [69]:
np.savetxt('tut.txt', arr, delimiter=",")
arr1 = np.loadtxt('tut.txt')
arr1

array([0.06491643, 0.99313402, 0.92211726, 0.17554249, 0.50925475,
       0.0553155 ])

In [79]:
import numpy as np
a=np.array([[9,6],[15,97]])
b=np.array([10,12])
np.linalg.solve(a,b)
np.linalg.inv(a)

array([[ 0.1238825 , -0.00766284],
       [-0.01915709,  0.01149425]])