In [14]:
import numpy as np
n1=np.ones(10)*5
n1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
type(n1)

numpy.ndarray

In [11]:
import numpy as np
n1=np.full((1,10),5)
n1

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [22]:
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
import numpy as np
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
np.vstack((n1,n2))
np.hstack((n1,n2))
np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
import numpy as np
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,2,9])
np.intersect1d(n1,n2)
np.setdiff1d(n1,n2)

array([1, 3, 4])

In [34]:
np.sum([n1,n2])
np.sum([n1,n2],axis=0)
np.sum([n1,n2],axis=1)

array([21, 37])

In [37]:
np.mean(n1)
np.std(n1)
np.median(n1)

3.5

In [41]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.save('n1Array',n1)

In [45]:
new_n1 = np.load('n1Array.npy')
new_n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])