In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
wine = load_wine()

In [ ]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
print("Inputs : ",wine.data)
print(wine.data.shape)
print("Input name : ",data.feature_names)
wine.feature_names = np.array(wine.feature_names)
print(wine.feature_names.shape)
print("Output : ",wine.target)
print(wine.target.shape)

Inputs :  [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
(178, 13)
Input name :  ['alcohol' 'malic_acid' 'ash' 'alcalinity_of_ash' 'magnesium'
 'total_phenols' 'flavanoids' 'nonflavanoid_phenols' 'proanthocyanins'
 'color_intensity' 'hue' 'od280/od315_of_diluted_wines' 'proline']
(13,)
Output :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2

In [ ]:
df = pd.DataFrame(wine.data, columns = [wine.feature_names])
df['target'] = wine.target
df

alcohol malic_acid   ash  ... od280/od315_of_diluted_wines proline target
0     14.23       1.71  2.43  ...                         3.92  1065.0      0
1     13.20       1.78  2.14  ...                         3.40  1050.0      0
2     13.16       2.36  2.67  ...                         3.17  1185.0      0
3     14.37       1.95  2.50  ...                         3.45  1480.0      0
4     13.24       2.59  2.87  ...                         2.93   735.0      0
..      ...        ...   ...  ...                          ...     ...    ...
173   13.71       5.65  2.45  ...                         1.74   740.0      2
174   13.40       3.91  2.48  ...                         1.56   750.0      2
175   13.27       4.28  2.26  ...                         1.56   835.0      2
176   13.17       2.59  2.37  ...                         1.62   840.0      2
177   14.13       4.10  2.74  ...                         1.60   560.0      2

[178 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()

In [ ]:
dat = scaling.fit_transform(df[df.columns])
df = pd.DataFrame(dat)
df

0         1         2         3   ...        10        11        12   13
0    0.842105  0.191700  0.572193  0.257732  ...  0.455285  0.970696  0.561341  0.0
1    0.571053  0.205534  0.417112  0.030928  ...  0.463415  0.780220  0.550642  0.0
2    0.560526  0.320158  0.700535  0.412371  ...  0.447154  0.695971  0.646933  0.0
3    0.878947  0.239130  0.609626  0.319588  ...  0.308943  0.798535  0.857347  0.0
4    0.581579  0.365613  0.807487  0.536082  ...  0.455285  0.608059  0.325963  0.0
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
173  0.705263  0.970356  0.582888  0.510309  ...  0.130081  0.172161  0.329529  1.0
174  0.623684  0.626482  0.598930  0.639175  ...  0.178862  0.106227  0.336662  1.0
175  0.589474  0.699605  0.481283  0.484536  ...  0.089431  0.106227  0.397290  1.0
176  0.563158  0.365613  0.540107  0.484536  ...  0.097561  0.128205  0.400856  1.0
177  0.815789  0.664032  0.737968  0.716495  ...  0.105691  0.120879  0.201141  1.0

[178 rows x 14 columns]

In [ ]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
class_0 = df[lambda v: v[13] == 0]
class_1 = df[lambda v: v[13] == 0.5]
class_2 = df[lambda v: v[13] == 1]

In [ ]:
print(class_0)

          0         1         2         3   ...        10        11        12   13
0   0.842105  0.191700  0.572193  0.257732  ...  0.455285  0.970696  0.561341  0.0
1   0.571053  0.205534  0.417112  0.030928  ...  0.463415  0.780220  0.550642  0.0
2   0.560526  0.320158  0.700535  0.412371  ...  0.447154  0.695971  0.646933  0.0
3   0.878947  0.239130  0.609626  0.319588  ...  0.308943  0.798535  0.857347  0.0
4   0.581579  0.365613  0.807487  0.536082  ...  0.455285  0.608059  0.325963  0.0
5   0.834211  0.201581  0.582888  0.237113  ...  0.463415  0.578755  0.835949  0.0
6   0.884211  0.223320  0.582888  0.206186  ...  0.439024  0.846154  0.721826  0.0
7   0.797368  0.278656  0.668449  0.360825  ...  0.471545  0.846154  0.725392  0.0
8   1.000000  0.177866  0.433155  0.175258  ...  0.487805  0.578755  0.547076  0.0
9   0.744737  0.120553  0.486631  0.278351  ...  0.430894  0.835165  0.547076  0.0
10  0.807895  0.280632  0.502674  0.381443  ...  0.626016  0.695971  0.878745  0.0
11  

In [ ]:
print(class_1)

           0         1         2         3   ...        10        11        12   13
59   0.352632  0.039526  0.000000  0.000000  ...  0.463415  0.201465  0.172611  0.5
60   0.342105  0.071146  0.491979  0.278351  ...  0.626016  0.146520  0.286733  0.5
61   0.423684  0.122530  0.352941  0.319588  ...  0.406504  0.117216  0.122682  0.5
62   0.694737  0.100791  0.299465  0.381443  ...  0.609756  0.435897  0.251070  0.5
63   0.352632  0.077075  0.427807  0.432990  ...  0.601626  0.586081  0.101284  0.5
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
125  0.273684  0.280632  0.433155  0.536082  ...  0.308943  0.736264  0.071327  0.5
126  0.368421  0.156126  0.497326  0.561856  ...  0.170732  0.575092  0.052782  0.5
127  0.200000  0.274704  0.759358  0.922680  ...  0.398374  0.428571  0.134094  0.5
128  0.352632  0.175889  0.502674  0.716495  ...  0.333333  0.553114  0.045649  0.5
129  0.265789  0.703557  0.545455  0.587629  ...  0.252033  0.476190  0.2154

In [ ]:
print(class_2)

           0         1         2         3   ...        10        11        12   13
130  0.481579  0.120553  0.513369  0.381443  ...  0.227642  0.007326  0.251070  1.0
131  0.486842  0.444664  0.556150  0.484536  ...  0.211382  0.054945  0.179743  1.0
132  0.468421  0.310277  0.556150  0.690722  ...  0.146341  0.032967  0.201141  1.0
133  0.439474  0.555336  0.534759  0.561856  ...  0.243902  0.007326  0.229672  1.0
134  0.389474  0.098814  0.475936  0.355670  ...  0.219512  0.087912  0.265335  1.0
135  0.413158  0.339921  0.449198  0.407216  ...  0.203252  0.113553  0.297432  1.0
136  0.321053  0.786561  0.631016  0.536082  ...  0.219512  0.000000  0.315264  1.0
137  0.394737  0.942688  0.684492  0.742268  ...  0.276423  0.153846  0.169044  1.0
138  0.647368  0.563241  0.443850  0.458763  ...  0.268293  0.201465  0.215407  1.0
139  0.476316  0.438735  0.668449  0.690722  ...  0.333333  0.322344  0.222539  1.0
140  0.500000  0.409091  0.716578  0.536082  ...  0.235772  0.380952  0.2296

In [ ]:
df[13]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
173    1.0
174    1.0
175    1.0
176    1.0
177    1.0
Name: 13, Length: 178, dtype: float64

In [ ]:
import numpy as np
def onehot(y):
  my = []
  for i in range(y.shape[0]):
    if y[i] == 0:
      my.append([1, 0, 0])
    if y[i] == 0.5:
      my.append([0, 1, 0])
    if y[i] == 1:
      my.append([0, 0, 1])

  my = np.array(my)

In [ ]:
onehot(df[13])

In [ ]:
X = data['data']
y = data['target']

In [ ]:
def perceptron(x_train, y_train):
 
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      
      weight = weight + x_train[index]
    if (y_train[index]==0 and hypothesis>=0):
      
      weight = weight - x_train[index]
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      
      score = predict(x_train, y_train, weight)
      if (score*100==100):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])