In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

In [ ]:
print("The dictonary keys are associated with data:\n", iris.keys())
print()
print("Data:\n", iris.data)
print()
print("Name of the features (Independent features): \n", iris.feature_names)
print()
print("Name of the dependent features: ", iris.target_names)
print()

The dictonary keys are associated with data:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3

## **1. Pre-process the data to use only 2 classes (Iris-Setosa and Iris-Versicolour)**

In [ ]:
y_actual = iris.target
y_actual = list(y_actual)
counter_setosa = 0
counter_versicolor = 0
counter_virginica = 0
for i in range(0,len(y_actual)):
  if(y_actual[i]==0):
    counter_setosa = counter_setosa  + 1 
  if(y_actual[i]==1):
    counter_versicolor = counter_versicolor + 1
  if(y_actual[i]==2):
    counter_virginica = counter_virginica + 1
print("Total no of patterns in setosa class",counter_setosa)
print("Total no of patterns in Versicolor class",counter_versicolor)
print("Total no of patterns in virginica class",counter_virginica)
# take only first 100 patterns
for i in range(0,50):
  y_actual.remove(2)
# covert it to an numpy array 
y_actual = np.array(y_actual)
print("After Preprocessing the data : ",y_actual.shape[0])

Total no of patterns in setosa class 50
Total no of patterns in Versicolor class 50
Total no of patterns in virginica class 50
After Preprocessing the data :  100



### take only first 100 patterns for the binary classification 

In [ ]:

features = list(iris.data)
print(len(features))
del features[100:]
print(len(features))
features = np.array(features)
print("No of the feature vectors: ",features.shape[1])
print("No of the Patterns: ",features.shape[0])

150
100
No of the feature vectors:  4
No of the Patterns:  100


### **2. Train test Split**
**train(70%), validation (10%), and test(20%)**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(features)
features = scaler.transform(features)

In [ ]:
# Train test validation
from sklearn.model_selection import train_test_split
import random

X_train, X_test, y_train, y_test = train_test_split(features,y_actual , test_size=0.3, random_state=random.randint(30,100))
X_test, X_validation, y_test, y_validation = train_test_split(X_test, y_test, test_size=0.14, random_state=random.randint(30,100))
print("Size of the train dataset:",X_train.shape)
print("Size of the validation dataset:",X_validation.shape)
print("Size of the test dataset:",X_test.shape)

Size of the train dataset: (70, 4)
Size of the validation dataset: (5, 4)
Size of the test dataset: (25, 4)


## **3. Hyperparameter tuning on the validation set**

**Sigmoid Function**

In [ ]:
def sigmoid(x):
  z = 1/(1+ np.exp(-x))
  return z;

**Gredient Descent algorithm**

In [ ]:
import numpy as np
import random

def gredient_descent(alpha, x, y, rho = 0.0001, max_itr = 10):
  converged = False
  itr = 0
  