####Name - Ranvijay Patel Amarnath <br>
####Roll No. - 1901156 <br>
####E-mail - ranvijay.amarnath@iiitg.ac.in

###1. Implement the perceptron algorithm for OR logic gate with 2-bit binary input

In [ ]:
import numpy as np
weight = np.array([1,1])
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
#bias = -0.5

###OR perceptron function

In [ ]:
def Perceptron(x, weight, bias):
  fx = np.dot(x, weight) + bias
  if fx >= 0:
    return i, 1
  else:
    return i, 0

###OR Perceptron


In [ ]:
print("OR Perceptron : \n")
for i in inputs:
  print(Perceptron(i, weight, -0.5))

OR Perceptron : 

(array([0, 0]), 0)
(array([0, 1]), 1)
(array([1, 0]), 1)
(array([1, 1]), 1)


###AND Perceptron

In [ ]:

for i in inputs:
  print(Perceptron(i, weight, -2))

(array([0, 0]), 0)
(array([0, 1]), 0)
(array([1, 0]), 0)
(array([1, 1]), 1)


##Algorithm implementation 

In [ ]:
import numpy as np

# weight = [w0, w1, w2] and bias = -0.5
w = np.array([0.1, 0.1, 0.1])

# w = [w0, w1, w2]
#x0 = 1
# xi = [[0,0],[0,1],[1,0][1,1]]
def Perceptron_Algo(w, x0, x ):
  hx = x0*w[0] + x[1]*w[1] + x[2]*w[2]
  if hx >= 0:
    y = 1;
  else:
    y = 0;
  xi = np.array([x0, x[1], x[2]])
  if hx >= 0:
    for x in xi:
      w = w - x
  else:
    w = w + x  
  
