Name - Ranvijay Patel<br/>
ROLL No - 1901156<br/>
Email - ranvijay.amarnath@iiitg.ac.in<br/>

# 1. Logic gate Implement using perceptron (AND, OR, Nand)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import warnings
from matplotlib import pyplot as plt
warnings.filterwarnings('default')
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, classification_report

In [ ]:
def predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  # x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  return test_acc

In [ ]:
def new_predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred)*100
  recall = recall_score(y_test, y_pred)*100
  f1 = f1_score(y_test, y_pred)*100
  print("Training Accuracy: ", test_acc)
  print("Prescission Score:", precision)
  print("Recall Score : ", recall) 
  print('F1 Score : ', f1)
  print('Confusion Matrix : \n' + str(confusion_matrix(y_test, y_pred)))
  print("Classification Report for 3-classes: ")
  print(classification_report(y_test, y_pred))
  # calculate the overall accuracy
  # print the confussion matrix
  # print the classification report
  return test_acc

In [ ]:
def add_intercept(x):
  intercept = np.ones((x.shape[0], 1))
  return np.concatenate((intercept, x), axis=1)
def perceptron(x_train, y_train, same_weight = False):
  # it uses only the threshold function (basic perceptron)
  # add intercept 
  x_train = add_intercept(x_train)
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  if (same_weight == True): # If we need to do the same weight initilization
    random.seed(10)
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  x_train, y_train = shuffle(x_train, y_train)  # shuffel the training sample
  index = random.randint(0, x_train.shape[0]-1)
  epoch = 1
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      # update the weight
      # w = w + x
      weight = weight + x_train[index]
    if (y_train[index]==0 and hypothesis>=0):
      # update the weight
      # w = w - x
      weight = weight - x_train[index]
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      # now check what is the accuracy now
      score = predict(x_train, y_train, weight)
      if (score*100==100):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

1.1. OR GATE

In [ ]:
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 1, 0, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

Epoch: 1
Epoch: 2
Epoch: 3
Epoch: 4
Epoch: 5
Epoch: 6
Succefully Converged:
Training Accuracy:  1.0
Prescission Score: 100.0
Recall Score :  100.0
F1 Score :  100.0
Confusion Matrix : 
[[1 0]
 [0 3]]
Classification Report for 3-classes: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



1.2. AND GATE

In [ ]:
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([0, 1, 0, 0])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

Epoch: 1
Epoch: 2
Epoch: 3
Epoch: 4
Epoch: 5
Epoch: 6
Epoch: 7
Epoch: 8
Epoch: 9
Epoch: 10
Epoch: 11
Epoch: 12
Epoch: 13
Epoch: 14
Epoch: 15
Epoch: 16
Epoch: 17
Epoch: 18
Epoch: 19
Epoch: 20
Succefully Converged:
Training Accuracy:  1.0
Prescission Score: 100.0
Recall Score :  100.0
F1 Score :  100.0
Confusion Matrix : 
[[3 0]
 [0 1]]
Classification Report for 3-classes: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



1.3. Nand Gate

In [ ]:
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 0, 1, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

Epoch: 1
Epoch: 2
Epoch: 3
Epoch: 4
Epoch: 5
Epoch: 6
Epoch: 7
Epoch: 8
Epoch: 9
Epoch: 10
Epoch: 11
Epoch: 12
Epoch: 13
Epoch: 14
Epoch: 15
Epoch: 16
Epoch: 17
Epoch: 18
Epoch: 19
Epoch: 20
Epoch: 21
Epoch: 22
Epoch: 23
Epoch: 24
Epoch: 25
Epoch: 26
Epoch: 27
Epoch: 28
Epoch: 29
Epoch: 30
Epoch: 31
Succefully Converged:
Training Accuracy:  1.0
Prescission Score: 100.0
Recall Score :  100.0
F1 Score :  100.0
Confusion Matrix : 
[[1 0]
 [0 3]]
Classification Report for 3-classes: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



1.4. XOR Gate

In [ ]:
def add_intercept(x):
  intercept = np.ones((x.shape[0], 1))
  return np.concatenate((intercept, x), axis=1)
def perceptron(x_train, y_train, same_weight = False):
  # it uses only the threshold function (basic perceptron)
  # add intercept 
  x_train = add_intercept(x_train)
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  if (same_weight == True): # If we need to do the same weight initilization
    random.seed(10)
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  x_train, y_train = shuffle(x_train, y_train)  # shuffel the training sample
  index = random.randint(0, x_train.shape[0]-1)
  epoch = 1
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      # update the weight
      # w = w + x
      weight = weight + x_train[index]
    if (y_train[index]==0 and hypothesis>=0):
      # update the weight
      # w = w - x
      weight = weight - x_train[index]
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      # now check what is the accuracy now
      score = predict(x_train, y_train, weight)
      if (score*100==75):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

In [ ]:
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 0, 0, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

Epoch: 1
Epoch: 2
Epoch: 3
Epoch: 4
Epoch: 5
Epoch: 6
Epoch: 7
Epoch: 8
Epoch: 9
Epoch: 10
Epoch: 11
Epoch: 12
Epoch: 13
Epoch: 14
Epoch: 15
Epoch: 16
Epoch: 17
Epoch: 18
Epoch: 19
Epoch: 20
Epoch: 21
Epoch: 22
Epoch: 23
Epoch: 24
Epoch: 25
Epoch: 26
Epoch: 27
Epoch: 28
Epoch: 29
Epoch: 30
Epoch: 31
Epoch: 32
Epoch: 33
Epoch: 34
Epoch: 35
Epoch: 36
Epoch: 37
Epoch: 38
Epoch: 39
Epoch: 40
Epoch: 41
Epoch: 42
Succefully Converged:
Training Accuracy:  0.75
Prescission Score: 66.66666666666666
Recall Score :  100.0
F1 Score :  80.0
Confusion Matrix : 
[[1 1]
 [0 2]]
Classification Report for 3-classes: 
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.67      1.00      0.80         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4



# 2. Real Attributes Classification 

In [ ]:
def sigmoid(z):
  return 1/(1 + np.exp(-z))

In [ ]:
def real_predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  # x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  # pass to the sigmoid one
  hypothesis = sigmoid(hypothesis)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  return test_acc 

In [ ]:
def add_intercept(x):
  intercept = np.ones((x.shape[0], 1))
  return np.concatenate((intercept, x), axis=1)
def real_perceptron(x_train, y_train, lr = 0.001, same_weight = False):
  # it uses only the threshold function (basic perceptron)
  # add intercept 
  x_train = add_intercept(x_train)
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  if (same_weight == True): # If we need to do the same weight initilization
    random.seed(10)
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  x_train, y_train = shuffle(x_train, y_train)  # shuffel the training sample
  index = random.randint(0, x_train.shape[0]-1)
  epoch = 1
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      # update the weight using logistic regression
      # w = w + alpha(h(xi)-yi)xi
      weight = weight + x_train[index]*lr*(hypothesis-y_train[index])
    if (y_train[index]==0 and hypothesis>=0):
      # update the weight using logistic regression
      # w = w - x
      weight = weight - x_train[index]*lr*(hypothesis-y_train[index])
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      # now check what is the accuracy now
      score = real_predict(x_train, y_train, weight)
      print("Score", score)
      if (score*100>=95):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

In [ ]:
print("The dictonary keys are associated with data:\n", iris.keys())
print("-"*100)
print("Data:\n", iris['data'])
print("-"*100)
print("Name of the features (Independent features): \n", iris['feature_names'])
print("-"*100)
print("Name of the dependent features: ", iris['target_names'])
print("-"*100)

The dictonary keys are associated with data:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
----------------------------------------------------------------------------------------------------
Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [

In [ ]:
# choose x and y 
y_actual = iris['target']
y_actual = list(y_actual)
counter_setosa = 0
counter_versicolor = 0
counter_virginica = 0
for i in range(0,len(y_actual)):
  if(y_actual[i]==0):
    counter_setosa = counter_setosa  + 1 
  if(y_actual[i]==1):
    counter_versicolor = counter_versicolor + 1
  if(y_actual[i]==2):
    counter_virginica = counter_virginica + 1
print("Total no of patterns in setosa class",counter_setosa)
print("Total no of patterns in versicolor class",counter_versicolor)
print("Total no of patterns in virginica class",counter_virginica)
# take only first 100 patterns
for i in range(0,50):
  y_actual.remove(2)
# covert it to an numpy array 
y_actual = np.array(y_actual)
print(y_actual.shape[0])

Total no of patterns in setosa class 50
Total no of patterns in versicolor class 50
Total no of patterns in virginica class 50
100


In [ ]:
# take only first 100 patterns for the binary classification 
features = list(iris['data'])
print(len(features))
del features[100:]
print(len(features))
features = np.array(features)
print("No of the feature vectors: %d"%features.shape[1])
print("No of the Patterns: %d"%features.shape[0])

150
100
No of the feature vectors: 4
No of the Patterns: 100


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(features)
features = scaler.transform(features)

In [ ]:
# Train test validation
from sklearn.model_selection import train_test_split
import random
# train(70%), validation (10%), and test(20%)
X_train, X_test, y_train, y_test = train_test_split(features,y_actual , test_size=0.3, random_state=random.randint(30,100))
X_test, X_validation, y_test, y_validation = train_test_split(X_test, y_test, test_size=0.14, random_state=random.randint(30,100))
print("Size of the train dataset:" + str(X_train.shape))
print("Size of the validation dataset:" + str(X_validation.shape))
print("Size of the test dataset:" + str(X_test.shape))

Size of the train dataset:(70, 4)
Size of the validation dataset:(5, 4)
Size of the test dataset:(25, 4)


In [ ]:
def real_test_predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  # pass to the sigmoid one
  hypothesis = sigmoid(hypothesis)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  return test_acc 

In [ ]:
weight  = real_perceptron(X_train, y_train, lr = 0.001, same_weight = False)

Streaming output truncated to the last 5000 lines.
Score 0.9428571428571428
Epoch: 22810
Score 0.9428571428571428
Epoch: 22811
Score 0.9428571428571428
Epoch: 22812
Score 0.9428571428571428
Epoch: 22813
Score 0.9428571428571428
Epoch: 22814
Score 0.9428571428571428
Epoch: 22815
Score 0.9428571428571428
Epoch: 22816
Score 0.9428571428571428
Epoch: 22817
Score 0.9428571428571428
Epoch: 22818
Score 0.9428571428571428
Epoch: 22819
Score 0.9428571428571428
Epoch: 22820
Score 0.9428571428571428
Epoch: 22821
Score 0.9428571428571428
Epoch: 22822
Score 0.9428571428571428
Epoch: 22823
Score 0.9428571428571428
Epoch: 22824
Score 0.9428571428571428
Epoch: 22825
Score 0.9428571428571428
Epoch: 22826
Score 0.9428571428571428
Epoch: 22827
Score 0.9428571428571428
Epoch: 22828
Score 0.9428571428571428
Epoch: 22829
Score 0.9428571428571428
Epoch: 22830
Score 0.9428571428571428
Epoch: 22831
Score 0.9428571428571428
Epoch: 22832
Score 0.9428571428571428
Epoch: 22833
Score 0.9428571428571428
Epoch: 22834

In [ ]:
weight

array([-0.04880595,  0.05180853,  0.00071577,  0.08173826,  0.08483168])

In [ ]:
acc = real_test_predict(X_test, y_test, weight)

In [ ]:
print("Test Accuracy:" ,acc*100)

Test Accuracy: 92.0


# Multi Class Classification

In [ ]:
def sigmoid(z):
  return 1/(1 + np.exp(-z))

In [ ]:
def multi_predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  # x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  # pass to the sigmoid one
  hypothesis = sigmoid(hypothesis)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  return test_acc 

In [ ]:
def add_intercept(x):
  intercept = np.ones((x.shape[0], 1))
  return np.concatenate((intercept, x), axis=1)
def multi_perceptron(x_train, y_train, lr = 0.001, same_weight = False):
  # it uses only the threshold function (basic perceptron)
  # add intercept 
  x_train = add_intercept(x_train)
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  if (same_weight == True): # If we need to do the same weight initilization
    random.seed(10)
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  x_train, y_train = shuffle(x_train, y_train)  # shuffel the training sample
  index = random.randint(0, x_train.shape[0]-1)
  epoch = 1
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      # update the weight using logistic regression
      # w = w + alpha(h(xi)-yi)xi
      weight = weight + x_train[index]*lr*(hypothesis-y_train[index])
    if (y_train[index]==0 and hypothesis>=0):
      # update the weight using logistic regression
      # w = w - x
      weight = weight - x_train[index]*lr*(hypothesis-y_train[index])
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      # now check what is the accuracy now
      score = real_predict(x_train, y_train, weight)
      print("Score", score)
      if (score*100>=95):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight